# Generated by Django 5.0.1 on 2024-03-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_id", models.CharField(max_length=255, verbose_name="category")),
                ("name", models.CharField(max_length=255, verbose_name="category")),
                ("is_active", models.BooleanField(default=False)),
                ("fin_time", models.DateTimeField(default=None, null=True)),
                ("num_posts", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.CharField()),
                ("rewrite", models.CharField(default=None, null=True)),
                ("img", models.CharField(default=None, null=True)),
                ("again", models.IntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewriteBot.mychannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rewriteBot.tguser"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mychannel",
            name="tg_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rewriteBot.tguser"
            ),
        ),
    ]
