# Generated by Django 5.0.1 on 2024-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewriteBot", "0002_alter_tguser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="again_post_id",
            field=models.CharField(default=None, null=True),
        ),
    ]
